AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  La Vanilla ID Backend

Parameters:
  StageName:
    Type: String
    Default: dev
    Description: The stage name for the API Gateway deployment (e.g., dev, prod).
  LogRetentionInDays:
    Type: Number
    Default: 7
    Description: CloudWatch Logs retention period in days
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]

Globals:
  Function:
    Timeout: 19
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON

Resources:
  LaVanillaTempBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "la-vanilla-temp-${StageName}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteTempObjects
            Status: Enabled
            ExpirationInDays: 1
      Tags:
        - Key: App
          Value: LaVanillaApp
  LaVanillaDraftOrderBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "la-vanilla-draft-order-${StageName}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: App
          Value: LaVanillaApp
  LaVanillaSelfServiceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "la-vanilla-self-service-${StageName}"
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: App
          Value: LaVanillaApp
  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "OAI for ${AWS::StackName}"

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref LaVanillaSelfServiceBucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub "${LaVanillaSelfServiceBucket.Arn}/*"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
          TargetOriginId: s3origin
          ViewerProtocolPolicy: https-only
          ForwardedValues:
            QueryString: false
        Origins:
          - Id: s3origin
            DomainName: !GetAtt LaVanillaSelfServiceBucket.DomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOAI}"

  LaVanillaApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref StageName
      Tags:
        App: LaVanillaApp

  # CloudWatch Log Groups with retention policy
  GraphqlLogGroup:
    Type: AWS::Logs::LogGroup
    DeletionPolicy: Retain
    Properties:
      LogGroupName: !Sub "/aws/lambda/${LaVanillaSelfServiceGraphql}"
      RetentionInDays: 7

  LaVanillaSelfServiceGraphql:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handlers/graphql-ss/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - arm64
      Events:
        CatchAll:
          Type: Api
          Properties:
            RestApiId: !Ref LaVanillaApi # Explicitly link to the API
            Path: /graphql-ss
            Method: POST
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: !GetAtt LaVanillaSelfServiceBucket.Arn
      Tags:
        App: LaVanillaApp

  LaVanillaSelfQueueGraphql:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handlers/graphql-sq/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - arm64
      Events:
        CatchAll:
          Type: Api
          Properties:
            RestApiId: !Ref LaVanillaApi # Explicitly link to the API
            Path: /graphql-sq
            Method: POST
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
              Resource:
                - !Sub "${LaVanillaSelfServiceBucket.Arn}/*"
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: !GetAtt LaVanillaSelfServiceBucket.Arn
      Tags:
        App: LaVanillaApp

  LaVanillaBackOfficeGraphql:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: handlers/graphql-backoffice/
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - arm64
      Events:
        CatchAll:
          Type: Api
          Properties:
            RestApiId: !Ref LaVanillaApi # Explicitly link to the API
            Path: /graphql-bo
            Method: POST
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
              Resource:
                - !Sub "${LaVanillaDraftOrderBucket.Arn}/*"
                - !Sub "${LaVanillaSelfServiceBucket.Arn}/*"
                - !Sub "${LaVanillaTempBucket.Arn}/*"
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: !GetAtt LaVanillaSelfServiceBucket.Arn
      Tags:
        App: LaVanillaApp

Outputs:
  Endpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${LaVanillaApi}.execute-api.${AWS::Region}.amazonaws.com/${StageName}/"
  LogRetention:
    Description: "CloudWatch Logs retention period"
    Value: !Sub "${LogRetentionInDays} days"
  CloudFrontURL:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt CloudFrontDistribution.DomainName