// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type File struct {
	Filename string  `json:"filename"`
	SizeInKb float64 `json:"sizeInKb"`
	URL      string  `json:"url"`
}

type Query struct {
}
