// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type File struct {
	Filename string `json:"filename"`
	Size     int    `json:"size"`
	URL      string `json:"url"`
}

type Query struct {
}
