// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package custom

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// CreateDraftOrderDraftOrderCreateDraftOrderResponse includes the requested fields of the GraphQL type DraftOrderResponse.
type CreateDraftOrderDraftOrderCreateDraftOrderResponse struct {
	DraftOrder CreateDraftOrderDraftOrderCreateDraftOrderResponseDraftOrder `json:"draftOrder"`
}

// GetDraftOrder returns CreateDraftOrderDraftOrderCreateDraftOrderResponse.DraftOrder, and is useful for accessing the field via an interface.
func (v *CreateDraftOrderDraftOrderCreateDraftOrderResponse) GetDraftOrder() CreateDraftOrderDraftOrderCreateDraftOrderResponseDraftOrder {
	return v.DraftOrder
}

// CreateDraftOrderDraftOrderCreateDraftOrderResponseDraftOrder includes the requested fields of the GraphQL type DraftOrder.
type CreateDraftOrderDraftOrderCreateDraftOrderResponseDraftOrder struct {
	Id string `json:"id"`
}

// GetId returns CreateDraftOrderDraftOrderCreateDraftOrderResponseDraftOrder.Id, and is useful for accessing the field via an interface.
func (v *CreateDraftOrderDraftOrderCreateDraftOrderResponseDraftOrder) GetId() string { return v.Id }

// CreateDraftOrderResponse is returned by CreateDraftOrder on success.
type CreateDraftOrderResponse struct {
	DraftOrderCreate CreateDraftOrderDraftOrderCreateDraftOrderResponse `json:"draftOrderCreate"`
}

// GetDraftOrderCreate returns CreateDraftOrderResponse.DraftOrderCreate, and is useful for accessing the field via an interface.
func (v *CreateDraftOrderResponse) GetDraftOrderCreate() CreateDraftOrderDraftOrderCreateDraftOrderResponse {
	return v.DraftOrderCreate
}

type DraftOrderInput struct {
	Email     string                    `json:"email"`
	LineItems []DraftOrderLineItemInput `json:"lineItems"`
}

// GetEmail returns DraftOrderInput.Email, and is useful for accessing the field via an interface.
func (v *DraftOrderInput) GetEmail() string { return v.Email }

// GetLineItems returns DraftOrderInput.LineItems, and is useful for accessing the field via an interface.
func (v *DraftOrderInput) GetLineItems() []DraftOrderLineItemInput { return v.LineItems }

type DraftOrderLineItemInput struct {
	VariantId string `json:"variantId"`
	Quantity  int    `json:"quantity"`
}

// GetVariantId returns DraftOrderLineItemInput.VariantId, and is useful for accessing the field via an interface.
func (v *DraftOrderLineItemInput) GetVariantId() string { return v.VariantId }

// GetQuantity returns DraftOrderLineItemInput.Quantity, and is useful for accessing the field via an interface.
func (v *DraftOrderLineItemInput) GetQuantity() int { return v.Quantity }

// __CreateDraftOrderInput is used internally by genqlient
type __CreateDraftOrderInput struct {
	Input DraftOrderInput `json:"input"`
}

// GetInput returns __CreateDraftOrderInput.Input, and is useful for accessing the field via an interface.
func (v *__CreateDraftOrderInput) GetInput() DraftOrderInput { return v.Input }

// The mutation executed by CreateDraftOrder.
const CreateDraftOrder_Operation = `
mutation CreateDraftOrder ($input: DraftOrderInput!) {
	draftOrderCreate(input: $input) {
		draftOrder {
			id
		}
	}
}
`

func CreateDraftOrder(
	ctx_ context.Context,
	client_ graphql.Client,
	input DraftOrderInput,
) (data_ *CreateDraftOrderResponse, err_ error) {
	req_ := &graphql.Request{
		OpName: "CreateDraftOrder",
		Query:  CreateDraftOrder_Operation,
		Variables: &__CreateDraftOrderInput{
			Input: input,
		},
	}

	data_ = &CreateDraftOrderResponse{}
	resp_ := &graphql.Response{Data: data_}

	err_ = client_.MakeRequest(
		ctx_,
		req_,
		resp_,
	)

	return data_, err_
}
