// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type PriceRange struct {
	MinVariantPrice *float64 `json:"minVariantPrice,omitempty"`
	MaxVariantPrice *float64 `json:"maxVariantPrice,omitempty"`
}

type Product struct {
	ID          string      `json:"id"`
	Description string      `json:"description"`
	PriceRange  *PriceRange `json:"priceRange"`
	Images      []string    `json:"images,omitempty"`
}

type Query struct {
}
