// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LineItem struct {
	VariantID string `json:"variantId"`
	Quantity  int    `json:"quantity"`
}

type Mutation struct {
}

type OrderInput struct {
	Items []*LineItem `json:"items"`
}

type PriceRange struct {
	MinVariantPrice *float64 `json:"minVariantPrice,omitempty"`
	MaxVariantPrice *float64 `json:"maxVariantPrice,omitempty"`
}

type Product struct {
	ID          string            `json:"id"`
	Title       string            `json:"title"`
	Description string            `json:"description"`
	PriceRange  *PriceRange       `json:"priceRange"`
	Images      []string          `json:"images,omitempty"`
	Variants    []*ProductVariant `json:"variants,omitempty"`
}

type ProductVariant struct {
	ID    string   `json:"id"`
	Title string   `json:"title"`
	Sku   string   `json:"sku"`
	Price float64  `json:"price"`
	Image []string `json:"image,omitempty"`
}

type Query struct {
}
