package backoffice

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"errors"
	"fmt"
	"lavanilla/graphql/backoffice/model"
	"lavanilla/service"
	"lavanilla/service/metadata"
	"lavanilla/service/shopify"
	"lavanilla/utils"
	"net/url"
	"strconv"
	"strings"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/aws/aws-sdk-go-v2/aws"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/samber/lo"
)

// DraftOrderStart is the resolver for the draftOrderStart field.
func (r *mutationResolver) DraftOrderStart(ctx context.Context, id string) (bool, error) {
	return r.DraftOrderHandler.Start(ctx, id)
}

// DraftOrderComplete is the resolver for the draftOrderComplete field.
func (r *mutationResolver) DraftOrderComplete(ctx context.Context, id string) (*model.Order, error) {
	return r.DraftOrderHandler.Complete(ctx, id)
}

// DraftOrderAddProductVariant is the resolver for the draftOrderAddProductVariant field.
func (r *mutationResolver) DraftOrderAddProductVariant(ctx context.Context, id string, variantID string, quantity int) (*model.Order, error) {
	return r.DraftOrderProductVariantHandler.Add(ctx, id, variantID, quantity)
}

// DraftOrderUpdateProductVariant is the resolver for the draftOrderUpdateProductVariant field.
func (r *mutationResolver) DraftOrderUpdateProductVariant(ctx context.Context, id string, variantID string, quantity int) (*model.Order, error) {
	return r.DraftOrderProductVariantHandler.Update(ctx, id, variantID, quantity)
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*model.Product, error) {
	productConn, err := r.ShopifyClient.GetProductsSelfService(ctx)
	if err != nil {
		return nil, err
	}
	var result []*model.Product
	for _, product := range productConn.Products.Edges {
		maxPrice, err := strconv.ParseFloat(product.Node.PriceRangeV2.MaxVariantPrice.Amount, 64)
		if err != nil {
			return nil, err
		}
		minPrice, err := strconv.ParseFloat(product.Node.PriceRangeV2.MinVariantPrice.Amount, 64)
		if err != nil {
			return nil, err
		}
		result = append(result, &model.Product{
			ID:          product.Node.Id,
			Title:       product.Node.Title,
			Description: product.Node.Description,
			PriceRange: &model.PriceRange{
				MaxVariantPrice: &maxPrice,
				MinVariantPrice: &minPrice,
			},
			Images: lo.Map(product.Node.Media.Nodes, func(imageEdge shopify.GetProductsSelfServiceProductsProductConnectionEdgesProductEdgeNodeProductMediaMediaConnectionNodesMedia, _ int) string {
				return imageEdge.GetPreview().Image.Url
			}),
		})
	}
	return result, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	productResp, err := r.ShopifyClient.GetProduct(ctx, id)
	if err != nil {
		return nil, err
	}
	return &model.Product{
		ID:          id,
		Description: productResp.Product.Description,
		Images: lo.Map(productResp.Product.Media.Nodes, func(imageEdge shopify.GetProductProductMediaMediaConnectionNodesMedia, _ int) string {
			return imageEdge.GetPreview().Image.Url
		}),
		Variants: lo.Map(productResp.Product.Variants.Nodes, func(variantEdge shopify.GetProductProductVariantsProductVariantConnectionNodesProductVariant, _ int) *model.ProductVariant {
			price, err := strconv.ParseFloat(variantEdge.Price, 64)
			if err != nil {
				price = 0
			}
			return &model.ProductVariant{
				ID:    variantEdge.Id,
				Title: variantEdge.Title,
				Sku:   variantEdge.Sku,
				Price: price,
			}
		}),
	}, nil
}

// DraftOrderDesigner is the resolver for the draftOrderDesigner field.
func (r *queryResolver) DraftOrderDesigner(ctx context.Context, status *model.DraftOrderStatus) ([]*model.Order, error) {
	return r.DraftOrderHandler.Find(ctx, status)
}

// DraftOrder is the resolver for the draftOrder field.
func (r *queryResolver) DraftOrder(ctx context.Context, draftOrderID string) (*model.Order, error) {
	_, draftOrderID, err := utils.ExtractIDWithDraftOrderPrefix(draftOrderID)
	if err != nil {
		return nil, err
	}

	order, err := r.ShopifyClient.GetDraftOrder(ctx, draftOrderID)
	if err != nil {
		return nil, err
	}

	s3resp, err := r.S3Client.ListObjectsV2(ctx, &s3.ListObjectsV2Input{
		Bucket: aws.String(service.S3BucketOrder),
		Prefix: aws.String(order.DraftOrder.Name),
	})
	if err != nil {
		return nil, errors.New(fmt.Sprintf("failed to list objects: %v", err))
	}

	objectMap := make(map[string][]string)
	for _, content := range s3resp.Contents {
		parts := strings.Split(*content.Key, "/")
		if len(parts) < 2 {
			continue
		}
		key := parts[1]
		objectMap[key] = append(objectMap[key], *content.Key)
	}

	fields := graphql.CollectFieldsCtx(ctx, nil)
	collectTimelines := false
	for _, field := range fields {
		if field.Name == "timelines" {
			collectTimelines = true
		}
	}

	var timelineData []metadata.Timeline
	if collectTimelines {
		timelineData, err = r.ShopifyClient.GetDraftOrderTimeline(ctx, draftOrderID)
		if err != nil {
			return nil, err
		}
	}

	return &model.Order{
		ID:   order.DraftOrder.Id,
		Name: order.DraftOrder.Name,
		LineItems: lo.Map(order.DraftOrder.LineItems.Nodes, func(item shopify.GetDraftOrderDraftOrderLineItemsDraftOrderLineItemConnectionNodesDraftOrderLineItem, _ int) *model.LineItem {
			foundImages, _ := objectMap[item.Sku]
			variantPrice, _ := strconv.ParseFloat(item.Variant.Price, 64)
			return &model.LineItem{
				Product: &model.Product{
					ID:    item.Id,
					Title: item.Title,
				},
				Quantity: item.Quantity,
				Variant: &model.ProductVariant{
					ID:    item.Variant.Id,
					Title: item.Variant.Title,
					Sku:   item.Variant.Sku,
					Price: variantPrice,
					Image: []string{item.Variant.Image.Url},
				},
				UploadedImages: lo.Map(foundImages, func(item string, _ int) string {
					return fmt.Sprintf("%s/%s", service.CdnOrder, url.QueryEscape(item))
				}),
			}
		}),
		Timelines: lo.Map(timelineData, func(item metadata.Timeline, _ int) *model.Timeline {
			return &model.Timeline{
				EventAt: item.Timestamp,
				Action:  model.EventAction(item.Action),
			}
		}),
	}, nil
}

// PresignedURLDesigner is the resolver for the presignedUrlDesigner field.
func (r *queryResolver) PresignedURLDesigner(ctx context.Context, orderName string, sku string, qty int) ([]string, error) {
	var result []string
	for i := 0; i < qty; i++ {
		filename := fmt.Sprintf("%s/%s/%d.jpeg", orderName, sku, time.Now().Unix()+1)
		object, err := r.S3PresignClient.PresignPutObject(ctx, &s3.PutObjectInput{
			Bucket:      aws.String(service.S3BucketOrder),
			ContentType: aws.String("image/jpeg"),
			Key:         aws.String(filename),
		}, func(options *s3.PresignOptions) {
			options.Expires = 15 * time.Minute
		})
		if err != nil {
			return nil, err
		}
		result = append(result, object.URL)
	}
	return result, nil
}

// DownloadAssetsDesigner is the resolver for the downloadAssetsDesigner field.
func (r *queryResolver) DownloadAssetsDesigner(ctx context.Context, draftOrderID string) (string, error) {
	result, err := r.DraftOrderHandler.DownloadAssetsDesigner(ctx, draftOrderID)
	if err != nil {
		return "", err
	}
	return *result, nil
}

// OrderPrintOperator is the resolver for the orderPrintOperator field.
func (r *queryResolver) OrderPrintOperator(ctx context.Context) ([]*model.Order, error) {
	orders, err := r.ShopifyClient.GetOrders(ctx)
	if err != nil {
		return nil, err
	}
	return lo.Map(orders.Orders.Nodes, func(item shopify.GetOrdersOrdersOrderConnectionNodesOrder, _ int) *model.Order {
		return &model.Order{
			ID:        item.Id,
			Name:      item.Name,
			CreatedAt: item.CreatedAt,
			Customer: &model.Customer{
				Name: item.Customer.DisplayName,
			},
		}
	}), nil
}

// Order is the resolver for the order field.
func (r *queryResolver) Order(ctx context.Context, orderID string) (*model.Order, error) {
	order, err := r.ShopifyClient.GetOrder(ctx, orderID)
	if err != nil {
		return nil, err
	}

	return &model.Order{
		ID:        order.Order.Id,
		Name:      order.Order.Name,
		CreatedAt: order.Order.CreatedAt,
		Customer: &model.Customer{
			Name: order.Order.Customer.DisplayName,
		},
		LineItems: lo.Map(order.Order.LineItems.Nodes, func(item shopify.GetOrderOrderLineItemsLineItemConnectionNodesLineItem, _ int) *model.LineItem {
			return &model.LineItem{
				Quantity: item.Quantity,
				Product: &model.Product{
					ID:    item.Product.Id,
					Title: item.Product.Title,
				},
				Variant: &model.ProductVariant{
					ID:  item.Id,
					Sku: item.Sku,
				},
			}
		}),
	}, nil
}

// DownloadAssetsPrintOperator is the resolver for the downloadAssetsPrintOperator field.
func (r *queryResolver) DownloadAssetsPrintOperator(ctx context.Context, orderID string, sku *string) (string, error) {
	return r.OrderHandler.DownloadAssetsPrintOperator(ctx, orderID, sku)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
