package self_service

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"lavanilla/graphql/self-service/model"
	"lavanilla/service/shopify"
	"strconv"

	"github.com/samber/lo"
)

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*model.Product, error) {
	productConn, err := r.ShopifyClient.GetProductsSelfService(ctx)
	if err != nil {
		return nil, err
	}
	var result []*model.Product
	for _, product := range productConn.Products.Edges {
		maxPrice, err := strconv.ParseFloat(product.Node.PriceRangeV2.MaxVariantPrice.Amount, 64)
		if err != nil {
			return nil, err
		}
		minPrice, err := strconv.ParseFloat(product.Node.PriceRangeV2.MinVariantPrice.Amount, 64)
		if err != nil {
			return nil, err
		}
		result = append(result, &model.Product{
			ID:          product.Node.Id,
			Description: product.Node.Description,
			PriceRange: &model.PriceRange{
				MaxVariantPrice: &maxPrice,
				MinVariantPrice: &minPrice,
			},
			Images: lo.Map(product.Node.Media.Nodes, func(imageEdge shopify.GetProductsSelfServiceProductsProductConnectionEdgesProductEdgeNodeProductMediaMediaConnectionNodesMedia, _ int) string {
				return imageEdge.GetPreview().Image.Url
			}),
		})
	}
	return result, nil
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	productResp, err := r.ShopifyClient.GetProduct(ctx, id)
	if err != nil {
		return nil, err
	}
	return &model.Product{
		ID:          id,
		Description: productResp.Product.Description,
		Images: lo.Map(productResp.Product.Media.Nodes, func(imageEdge shopify.GetProductProductMediaMediaConnectionNodesMedia, _ int) string {
			return imageEdge.GetPreview().Image.Url
		}),
	}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
