package self_service

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"fmt"
	"lavanilla/graphql/self-service/model"
	"lavanilla/service/shopify"
	"strconv"

	"github.com/samber/lo"
)

// Ok is the resolver for the ok field.
func (r *queryResolver) Ok(ctx context.Context) (bool, error) {
	panic(fmt.Errorf("not implemented: Ok - ok"))
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context) ([]*model.Product, error) {
	client := shopify.NewClient()
	productConn, err := client.GetProductsSelfService(ctx)
	if err != nil {
		return nil, err
	}
	var result []*model.Product
	for _, product := range productConn.Products.Edges {
		maxPrice, err := strconv.ParseFloat(product.Node.PriceRangeV2.MaxVariantPrice.Amount, 64)
		if err != nil {
			return nil, err
		}
		minPrice, err := strconv.ParseFloat(product.Node.PriceRangeV2.MinVariantPrice.Amount, 64)
		if err != nil {
			return nil, err
		}
		result = append(result, &model.Product{
			ID:          product.Node.Id,
			Description: product.Node.Description,
			PriceRange: &model.PriceRange{
				MaxVariantPrice: &maxPrice,
				MinVariantPrice: &minPrice,
			},
			Images: lo.Map(product.Node.Media.Nodes, func(imageEdge shopify.GetProductsSelfServiceProductsProductConnectionEdgesProductEdgeNodeProductMediaMediaConnectionNodesMedia, _ int) string {
				return imageEdge.GetPreview().Image.Url
			}),
		})
	}
	return result, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
