name: Deploy main to dev
on:
  push:
    branches: [ main ]

jobs:
  build_deploy_graphql:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - run: make all

      - run: sam build

      - run: sam deploy --config-env development AppEnv=DEV --resolve-s3 --stack-name lavanilla-backend-dev
