name: Deploy main to dev
on:
  push:
    branches: [ main ]

jobs:
  build_deploy_graphql:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build Go Lambdas
        run: |
          for func in graphql-ss graphql-sq graphql-backoffice; do
            echo "Building $func..."
            cd handlers/$func
            GOOS=linux GOARCH=arm64 go build -o bootstrap main.go
            cd ../../
          done

      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli

      - run: sam build

      - run: sam deploy --stack-name lavanilla-backend-dev --config-env dev --resolve-s3 --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --parameter-overrides AppEnv=DEV --no-confirm-changeset --no-fail-on-empty-changeset